name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add stable x86_64-unknown-linux-musl target
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: x86_64-unknown-linux-musl
          components: rustfmt, clippy

      - name: Cache Build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cargo Test
        run: |
          cargo test

      - name: Cargo Clippy
        run: |
          cargo clippy -- -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used

      - name: Cargo Build Binary (x86_64-unknown-linux-gnu)
        run: |
          cargo build --release
          chmod +x target/release/${{ github.event.repository.name }}

      - name: Cargo Build Binary (x86_64-unknown-linux-musl)
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          chmod +x target/x86_64-unknown-linux-musl/release/${{ github.event.repository.name }}

      - name: Optimize Binaries with UPX
        run: |
          upx --best --lzma target/release/${{ github.event.repository.name }}
          upx --best --lzma target/x86_64-unknown-linux-musl/release/${{ github.event.repository.name }}

      - name: Package Binaries
        run: |
          toolchain=$(rustup toolchain list | awk '{print $1;}')
          tar_name="${{ github.event.repository.name }}_${{ github.ref_name }}-$toolchain"
          tar -cvzf target/release/$tar_name.tar.gz target/release/${{ github.event.repository.name }}
          tar_name="${{ github.event.repository.name }}_${{ github.ref_name }}-x86_64-unknown-linux-musl"
          tar -cvzf target/release/$tar_name.tar.gz target/x86_64-unknown-linux-musl/release/${{ github.event.repository.name }}

      - name: Release
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: CHANGELOG.md
        with:
          args: |
            target/release/*.tar.gz
